fix(core): add utils conditional test
mathisscott/clarity pull request #11
Opened 2021-09-08 13:36 UTC by bbogdanov

2021-09-08 13:37 UTC, bbogdanov commented on packages/core/src/internal/utils/conditional.ts
> +  const mapOfUntruth = untruths.map((fn: BoolFn) => fn());
`fn()` returns a boolean, so I assume we can skip the additional check

2021-09-08 18:29 UTC, mathisscott requested changes

2021-09-08 18:29 UTC, mathisscott commented on packages/core/src/internal/utils/conditional.spec.ts
> +      const truths = [
You could improve this code by have shared consts across all tests, instead of redefining the consts for every test

2021-09-08 18:29 UTC, mathisscott commented on packages/core/src/internal/utils/conditional.ts
> +  const mapOfUntruth = untruths.map((fn: BoolFn) => fn());
that assumes that the end user supplies us with a true/false function. i'm fine with this change but noting that we may see it "break" in the future when some end user doesn't cover all their bases and returns undefined...

2021-09-09 06:49 UTC, bbogdanov commented on packages/core/src/internal/utils/conditional.ts
> +  const mapOfUntruth = untruths.map((fn: BoolFn) => fn());
Even if they return `undefined`, the behaviour of the `if` on the next line won't change.

2021-09-09 12:54 UTC, mathisscott approved these changes

2021-09-09 12:54 UTC, merged